// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/features": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/deposit": {
    params: {};
  };
  "/cards": {
    params: {};
  };
  "/valid": {
    params: {};
  };
  "/valid-guarantee": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/history": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/x9k7-secure-admin-core-portal-88421": {
    params: {};
  };
  "/x9k7-secure-admin-core-portal-88421/login": {
    params: {};
  };
  "/panel-entry": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/login": {
    params: {};
  };
  "/x7k9-secure-panel-god/login": {
    params: {};
  };
  "/x7k9-secure-panel-god": {
    params: {};
  };
  "/api/register": {
    params: {};
  };
  "/api/reset-password": {
    params: {};
  };
  "/api/login": {
    params: {};
  };
  "/api/user": {
    params: {};
  };
  "/api/orders": {
    params: {};
  };
  "/api/products": {
    params: {};
  };
  "/api/buy": {
    params: {};
  };
  "/api/deposit/create": {
    params: {};
  };
  "/api/deposit/callback": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/api/admin-auth": {
    params: {};
  };
  "/api/admin": {
    params: {};
  };
  "/api/support": {
    params: {};
  };
  "/api/wallet": {
    params: {};
  };
  "/only-god-access-x9k2": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/reset-password" | "/support" | "/features" | "/products" | "/dashboard" | "/deposit" | "/cards" | "/valid" | "/valid-guarantee" | "/orders" | "/history" | "/cart" | "/x9k7-secure-admin-core-portal-88421" | "/x9k7-secure-admin-core-portal-88421/login" | "/panel-entry" | "/admin" | "/admin/login" | "/x7k9-secure-panel-god/login" | "/x7k9-secure-panel-god" | "/api/register" | "/api/reset-password" | "/api/login" | "/api/user" | "/api/orders" | "/api/products" | "/api/buy" | "/api/deposit/create" | "/api/deposit/callback" | "/api/health" | "/api/admin-auth" | "/api/admin" | "/api/support" | "/api/wallet" | "/only-god-access-x9k2";
  };
  "routes/public-layout.tsx": {
    id: "routes/public-layout";
    page: "/" | "/login" | "/register" | "/reset-password" | "/support" | "/features" | "/products";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/reset-password.tsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/support.tsx": {
    id: "routes/support";
    page: "/support";
  };
  "routes/redirect-home-features.ts": {
    id: "routes/redirect-home-features";
    page: "/features";
  };
  "routes/redirect-home-products.ts": {
    id: "routes/redirect-home-products";
    page: "/products";
  };
  "routes/dashboard-layout.tsx": {
    id: "routes/dashboard-layout";
    page: "/dashboard" | "/deposit" | "/cards" | "/valid" | "/valid-guarantee" | "/orders" | "/history" | "/cart";
  };
  "routes/user-dashboard.tsx": {
    id: "routes/user-dashboard";
    page: "/dashboard";
  };
  "routes/wallet-deposit.tsx": {
    id: "routes/wallet-deposit";
    page: "/deposit";
  };
  "routes/cards-catalog.tsx": {
    id: "routes/cards-catalog";
    page: "/cards";
  };
  "routes/valid-cc.tsx": {
    id: "routes/valid-cc";
    page: "/valid";
  };
  "routes/valid-guarantee.tsx": {
    id: "routes/valid-guarantee";
    page: "/valid-guarantee";
  };
  "routes/my-orders.tsx": {
    id: "routes/my-orders";
    page: "/orders";
  };
  "routes/transaction-history.tsx": {
    id: "routes/transaction-history";
    page: "/history";
  };
  "routes/my-cart.tsx": {
    id: "routes/my-cart";
    page: "/cart";
  };
  "routes/admin-landing.tsx": {
    id: "routes/admin-landing";
    page: "/x9k7-secure-admin-core-portal-88421";
  };
  "routes/admin-login.tsx": {
    id: "routes/admin-login";
    page: "/x9k7-secure-admin-core-portal-88421/login";
  };
  "routes/admin-legacy-panel-entry-redirect.tsx": {
    id: "routes/admin-legacy-panel-entry-redirect";
    page: "/panel-entry";
  };
  "routes/admin-legacy-redirect.tsx": {
    id: "routes/admin-legacy-redirect";
    page: "/admin";
  };
  "routes/admin-legacy-login-redirect.tsx": {
    id: "routes/admin-legacy-login-redirect";
    page: "/admin/login";
  };
  "routes/admin-legacy-hidden-login-redirect.tsx": {
    id: "routes/admin-legacy-hidden-login-redirect";
    page: "/x7k9-secure-panel-god/login";
  };
  "routes/admin-portal.tsx": {
    id: "routes/admin-portal";
    page: "/x7k9-secure-panel-god";
  };
  "routes/api.register.ts": {
    id: "routes/api.register";
    page: "/api/register";
  };
  "routes/api.reset-password.ts": {
    id: "routes/api.reset-password";
    page: "/api/reset-password";
  };
  "routes/api.login.ts": {
    id: "routes/api.login";
    page: "/api/login";
  };
  "routes/api.user.ts": {
    id: "routes/api.user";
    page: "/api/user";
  };
  "routes/api.orders.ts": {
    id: "routes/api.orders";
    page: "/api/orders";
  };
  "routes/api.products.ts": {
    id: "routes/api.products";
    page: "/api/products";
  };
  "routes/api.buy.ts": {
    id: "routes/api.buy";
    page: "/api/buy";
  };
  "routes/api.deposit.create.ts": {
    id: "routes/api.deposit.create";
    page: "/api/deposit/create";
  };
  "routes/api.deposit.callback.ts": {
    id: "routes/api.deposit.callback";
    page: "/api/deposit/callback";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/api.admin-auth.ts": {
    id: "routes/api.admin-auth";
    page: "/api/admin-auth";
  };
  "routes/api.admin.ts": {
    id: "routes/api.admin";
    page: "/api/admin";
  };
  "routes/api.support.ts": {
    id: "routes/api.support";
    page: "/api/support";
  };
  "routes/api.wallet.ts": {
    id: "routes/api.wallet";
    page: "/api/wallet";
  };
  "routes/only-god-access-x9k2.tsx": {
    id: "routes/only-god-access-x9k2";
    page: "/only-god-access-x9k2";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/public-layout": typeof import("./app/routes/public-layout.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.tsx");
  "routes/support": typeof import("./app/routes/support.tsx");
  "routes/redirect-home-features": typeof import("./app/routes/redirect-home-features.ts");
  "routes/redirect-home-products": typeof import("./app/routes/redirect-home-products.ts");
  "routes/dashboard-layout": typeof import("./app/routes/dashboard-layout.tsx");
  "routes/user-dashboard": typeof import("./app/routes/user-dashboard.tsx");
  "routes/wallet-deposit": typeof import("./app/routes/wallet-deposit.tsx");
  "routes/cards-catalog": typeof import("./app/routes/cards-catalog.tsx");
  "routes/valid-cc": typeof import("./app/routes/valid-cc.tsx");
  "routes/valid-guarantee": typeof import("./app/routes/valid-guarantee.tsx");
  "routes/my-orders": typeof import("./app/routes/my-orders.tsx");
  "routes/transaction-history": typeof import("./app/routes/transaction-history.tsx");
  "routes/my-cart": typeof import("./app/routes/my-cart.tsx");
  "routes/admin-landing": typeof import("./app/routes/admin-landing.tsx");
  "routes/admin-login": typeof import("./app/routes/admin-login.tsx");
  "routes/admin-legacy-panel-entry-redirect": typeof import("./app/routes/admin-legacy-panel-entry-redirect.tsx");
  "routes/admin-legacy-redirect": typeof import("./app/routes/admin-legacy-redirect.tsx");
  "routes/admin-legacy-login-redirect": typeof import("./app/routes/admin-legacy-login-redirect.tsx");
  "routes/admin-legacy-hidden-login-redirect": typeof import("./app/routes/admin-legacy-hidden-login-redirect.tsx");
  "routes/admin-portal": typeof import("./app/routes/admin-portal.tsx");
  "routes/api.register": typeof import("./app/routes/api.register.ts");
  "routes/api.reset-password": typeof import("./app/routes/api.reset-password.ts");
  "routes/api.login": typeof import("./app/routes/api.login.ts");
  "routes/api.user": typeof import("./app/routes/api.user.ts");
  "routes/api.orders": typeof import("./app/routes/api.orders.ts");
  "routes/api.products": typeof import("./app/routes/api.products.ts");
  "routes/api.buy": typeof import("./app/routes/api.buy.ts");
  "routes/api.deposit.create": typeof import("./app/routes/api.deposit.create.ts");
  "routes/api.deposit.callback": typeof import("./app/routes/api.deposit.callback.ts");
  "routes/api.health": typeof import("./app/routes/api.health.ts");
  "routes/api.admin-auth": typeof import("./app/routes/api.admin-auth.ts");
  "routes/api.admin": typeof import("./app/routes/api.admin.ts");
  "routes/api.support": typeof import("./app/routes/api.support.ts");
  "routes/api.wallet": typeof import("./app/routes/api.wallet.ts");
  "routes/only-god-access-x9k2": typeof import("./app/routes/only-god-access-x9k2.tsx");
};