// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/features": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/deposit": {
    params: {};
  };
  "/cards": {
    params: {};
  };
  "/valid": {
    params: {};
  };
  "/valid-guarantee": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/history": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/x9k7-secure-admin-core-portal-88421": {
    params: {};
  };
  "/x9k7-secure-admin-core-portal-88421/login": {
    params: {};
  };
  "/panel-entry": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/login": {
    params: {};
  };
  "/x7k9-secure-panel-god/login": {
    params: {};
  };
  "/x7k9-secure-panel-god": {
    params: {};
  };
  "/only-god-access-x9k2": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/reset-password" | "/support" | "/features" | "/products" | "/dashboard" | "/deposit" | "/cards" | "/valid" | "/valid-guarantee" | "/orders" | "/history" | "/cart" | "/x9k7-secure-admin-core-portal-88421" | "/x9k7-secure-admin-core-portal-88421/login" | "/panel-entry" | "/admin" | "/admin/login" | "/x7k9-secure-panel-god/login" | "/x7k9-secure-panel-god" | "/only-god-access-x9k2";
  };
  "routes/public-layout.tsx": {
    id: "routes/public-layout";
    page: "/" | "/login" | "/register" | "/reset-password" | "/support" | "/features" | "/products";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/reset-password.tsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/support.tsx": {
    id: "routes/support";
    page: "/support";
  };
  "routes/redirect-home-features.ts": {
    id: "routes/redirect-home-features";
    page: "/features";
  };
  "routes/redirect-home-products.ts": {
    id: "routes/redirect-home-products";
    page: "/products";
  };
  "routes/dashboard-layout.tsx": {
    id: "routes/dashboard-layout";
    page: "/dashboard" | "/deposit" | "/cards" | "/valid" | "/valid-guarantee" | "/orders" | "/history" | "/cart";
  };
  "routes/user-dashboard.tsx": {
    id: "routes/user-dashboard";
    page: "/dashboard";
  };
  "routes/wallet-deposit.tsx": {
    id: "routes/wallet-deposit";
    page: "/deposit";
  };
  "routes/cards-catalog.tsx": {
    id: "routes/cards-catalog";
    page: "/cards";
  };
  "routes/valid-cc.tsx": {
    id: "routes/valid-cc";
    page: "/valid";
  };
  "routes/valid-guarantee.tsx": {
    id: "routes/valid-guarantee";
    page: "/valid-guarantee";
  };
  "routes/my-orders.tsx": {
    id: "routes/my-orders";
    page: "/orders";
  };
  "routes/transaction-history.tsx": {
    id: "routes/transaction-history";
    page: "/history";
  };
  "routes/my-cart.tsx": {
    id: "routes/my-cart";
    page: "/cart";
  };
  "routes/admin-landing.tsx": {
    id: "routes/admin-landing";
    page: "/x9k7-secure-admin-core-portal-88421";
  };
  "routes/admin-login.tsx": {
    id: "routes/admin-login";
    page: "/x9k7-secure-admin-core-portal-88421/login";
  };
  "routes/admin-legacy-panel-entry-redirect.tsx": {
    id: "routes/admin-legacy-panel-entry-redirect";
    page: "/panel-entry";
  };
  "routes/admin-legacy-redirect.tsx": {
    id: "routes/admin-legacy-redirect";
    page: "/admin";
  };
  "routes/admin-legacy-login-redirect.tsx": {
    id: "routes/admin-legacy-login-redirect";
    page: "/admin/login";
  };
  "routes/admin-legacy-hidden-login-redirect.tsx": {
    id: "routes/admin-legacy-hidden-login-redirect";
    page: "/x7k9-secure-panel-god/login";
  };
  "routes/admin-portal.tsx": {
    id: "routes/admin-portal";
    page: "/x7k9-secure-panel-god";
  };
  "routes/only-god-access-x9k2.tsx": {
    id: "routes/only-god-access-x9k2";
    page: "/only-god-access-x9k2";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/public-layout": typeof import("./app/routes/public-layout.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.tsx");
  "routes/support": typeof import("./app/routes/support.tsx");
  "routes/redirect-home-features": typeof import("./app/routes/redirect-home-features.ts");
  "routes/redirect-home-products": typeof import("./app/routes/redirect-home-products.ts");
  "routes/dashboard-layout": typeof import("./app/routes/dashboard-layout.tsx");
  "routes/user-dashboard": typeof import("./app/routes/user-dashboard.tsx");
  "routes/wallet-deposit": typeof import("./app/routes/wallet-deposit.tsx");
  "routes/cards-catalog": typeof import("./app/routes/cards-catalog.tsx");
  "routes/valid-cc": typeof import("./app/routes/valid-cc.tsx");
  "routes/valid-guarantee": typeof import("./app/routes/valid-guarantee.tsx");
  "routes/my-orders": typeof import("./app/routes/my-orders.tsx");
  "routes/transaction-history": typeof import("./app/routes/transaction-history.tsx");
  "routes/my-cart": typeof import("./app/routes/my-cart.tsx");
  "routes/admin-landing": typeof import("./app/routes/admin-landing.tsx");
  "routes/admin-login": typeof import("./app/routes/admin-login.tsx");
  "routes/admin-legacy-panel-entry-redirect": typeof import("./app/routes/admin-legacy-panel-entry-redirect.tsx");
  "routes/admin-legacy-redirect": typeof import("./app/routes/admin-legacy-redirect.tsx");
  "routes/admin-legacy-login-redirect": typeof import("./app/routes/admin-legacy-login-redirect.tsx");
  "routes/admin-legacy-hidden-login-redirect": typeof import("./app/routes/admin-legacy-hidden-login-redirect.tsx");
  "routes/admin-portal": typeof import("./app/routes/admin-portal.tsx");
  "routes/only-god-access-x9k2": typeof import("./app/routes/only-god-access-x9k2.tsx");
};